#! /usr/bin/env python3

import os
import sys
from GenLoggerFrame import *

class GenTestApp(wx.App):
    def OnInit(self):
        self.main = GenLoggerFrame(None)
        self.main.Show()
        self.SetTopWindow(self.main)
        return True

def main():
    application = GenTestApp(0)
    application.MainLoop()

if __name__ == '__main__':
    main()

